name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Test Go Code
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

  styles:
    name: Style
    runs-on: ubuntu-latest

    steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Install Staticcheck
          uses: dominikh/staticcheck-action@v1
          with:
            version: "latest"
            install-go: false

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
           go-version: "1.23.0"

        - name: Run Staticcheck
          run: staticcheck ./...

        - name: Style check Go Code
          run: test -z $(go fmt ./...)